### ISSUE TITLE
Clicking emeralds does not turn them into player XP

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/AnsibleSetup#34]
Likely config issue

**Comment by Protonull** [comment]
This is an odd issue.

Emerald levelling requires both `emerald_crafting` and `emerald_leveling` enabled in OldEnchanting's config. What's curious is that the values default to true (as shown [here](https://github.com/CivClassic/OldEnchanting/blob/master/src/main/resources/config.yml#L24)) and the config parser defaults them to true if the values are missing (as shown [here](https://github.com/CivClassic/OldEnchanting/blob/master/src/main/java/com/civclassic/oldenchanting/OldEnchanting.java#L206)), and the Ansible config has both values set to true (as shown [here](https://github.com/CivClassic/AnsibleSetup/blob/master/templates/public/plugins/OldEnchanting/config.yml.j2#L21)).

I don't think it's a config issue, I think something is happening with that event.

**Comment by Protonull** [comment]
While creating a [small bugfix](https://github.com/CivClassic/OldEnchanting/pull/7/files) (merge plox), I noticed how the bug only existed when using the jar within the AnsibleSetup repo (which was downloaded only a few hours ago), which also appears to have an outdated CivModCore jar (since it lacked `itemAPI.decrementItem();`. I think fixing this issue will be as easy as compiling new jars.

**Comment by Maxopoly** [comment]
Fixed by updating jars
