### ISSUE TITLE
Consider adding TradePlus

### ISSUE THREAD

**Issue by Protonull** [CivClassic/AnsibleSetup#48]
[TradePlus](https://github.com/Trophonix/TradePlus) was used on CivEx prior to and then concurrent with my ShopExchange plugin to facilitate trade. It presents a World of Warcraft like [trade window](https://imgur.com/Jf0G8Qz) to the requested player, assuming they accept the trade request.

I'm suggesting this because in-person trades can get a little awkward. You either set up a shop chest for the exact items to trade and hope there's no deviancy that you may agree to (which becomes infinitely more difficult if you're exchanging multiple items for multiple items) or you can both throw your items on the ground or at each other.

What this plugin would do, when configured, is allow for informed trading. You see *exactly* what items you'll receive and in what amount, and so do they. It doesn't remove physicality (unless configured), people would still be trading in person and all the risks that entails... all it would do is allow for easier more informed trading.

This is by no means meant to replace ItemExchange, just fill in the gaps of in person trading.

**Comment by Maxopoly** [comment]
Addressed by https://github.com/CivClassic/AnsibleSetup/commit/edfd101a1d3f728b3087f84d028843b91439bde0
Would be cool if you could figure out how to build that thing on our own, because I couldn't. If we need to update it in the future we'd likely want to fork and rip out all the random BS dependencies the same way we did with Brewery.
